version: '3'

services:
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/hosts:/etc/hosts
      - ./nginx/static:/static
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

  client:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command:
      - sh
      - -c
      - |
        (cd client; npm run start)

  server:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    command:
      - sh
      - -c
      - |
        (cd server; npm run start)