name: default

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  default:
    runs-on: ubuntu-latest
  
  steps:
    # get repo code
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    # same as npm i
    - run: npm ci
    - run: npm test
    - run: npm run lint